server:
    port: 9210
spring:
    application:
        name: ${project.artifactId}
        version: ${project.version}
    cloud:
        sentinel:
            transport:
                port: 9212
mybatis:
    basepackage: com.donkeycode.data.mapper
    xmlLocation: classpath:mapper/**/*.xml
    mapper-locations: classpath*:mapper/*.xml
# mapper
mapper:
    not-empty: false
    identity: MYSQL
    safeDelete: true
    safeUpdate: true
    mappers: com.donkeycode.boot.utils.BaseMapper
# mapper pagehelper page.
pagehelper:
    autoDialect: true
    closeConn: true
    offset-as-page-num: false
feign:
    sentinel:
        enabled: true
    httpclient:
        enabled: false
    okhttp:
        enabled: true
    compression:
        request:
            enabled: true
            mime-types: text/xml,application/xml,application/json
            min-request-size: 2048
        response:
            enabled: true
