spring:
    cloud:
        gateway:
            discovery:
                locator:
                    lowerCaseServiceId: true
                    enabled: true
            routes:
            # =====================================
            -   id: donkey-cloud-auth
                uri: lb://donkey-cloud-auth
                order: 8000
                predicates:
                - Path=/api/auth/**
                filters:
                - StripPrefix=2
            -   id: donkey-cloud-admin
                uri: lb://donkey-cloud-admin
                order: 8001
                predicates:
                - Path=/api/admin/**
                filters:
                - StripPrefix=2
            -   id: donkey-cloud-acl
                uri: lb://donkey-cloud-acl
                order: 8002
                predicates:
                - Path=/api/acl/**
                filters:
                - StripPrefix=2
        nacos:
            discovery:
                server-addr: 192.168.2.102:8848
        sentinel:
            transport:
                dashboard: 192.168.2.102:8080
management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: ALWAYS
gate:
    ignore:
        startWith: /auth/jwt
auth:
    serviceId: donkey-cloud-auth
    user:
        token-header: Authorization
    client:
        token-header: x-client-token
        id: donkey-cloud-gateway
        secret: 123456
